---
title: "Vision and Scope: `model-flow`"
author: "Alex Abraham"
date: "2024"
output: 
  pdf_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Business Requirements

### Problem Definition

For data practitioners and business managers,
there's predictable and significant waste when formulating predictive models.

- Coders and business managers waste time (dollars) 
misaligned on, or searching for, critical process details. 
  - "What data observations are we including/excluding?"
  - "Which model features are we including/excluding?"
  - "What transformation functions are treating the model features?" 
  - "Could we try the analysis with ___ details changed? 
  How does that result compare with other analyses we've tried?"
  - "In this ensemble, what models are included, and what are their details?"
  - "Where in the code is _____ implemented?"

- Coders waste time (dollars) re-building _transform pipelines_,
  - project-to-project, or
  - within-project, moving to production from R&D.
  - Technical debt compounds with unnecessary idiosyncrasies. 

There's significant opportunity for pipeline code reuse, project-to-project. 
There's significant opportunity to standardize and de-couple components:
(a) transforms workflow from (b) project-specific configuration. 

In 2024, ad hoc Data Science (DS) workflows severely reduce potential impact.
"What got you here won't get you there." 
Democratized cloud computing allows DS to _ascend the value chain_: 
to actually deploy workflows (products), not just research and develop. 
Ad hoc workflows are expensive to deploy and maintain. 

DS code has tended more _ad hoc_ than classic software engineering. 
Part of the explanation is product development 101: given uncertain direction,
builders rapidly prototype, wary of wasting effort on dead ends.
Another partial explanation: practitioners may train in subject matter domains 
(economics, biology, mathematics, physics), more than engineering principles.

### Objectives

- Reduce time-until-baseline model (primarily construction time)
- Reduce time-until-answer for stakeholders' questions about model details
- Reduce errors in feature transform pipeline
- Reduce costs of model maintenance and modification
- Reduce model's time-until-production

### Metrics (Key Results)

Decrease:

- work hours between requirements definition and baseline model results
- work hours pursuing answers to stakeholder questions
- issues count for feature transform pipeline
- work hours inspecting and extending pipeline behavior
- work hours productionizing R&D pipeline code

### Vision Statement

Model developers' productivity will surge, 
as code construction time plummets and architecture cohesion rises. 
Model developers will more easily maintain & extend a modeling _system_.

Business managers' return on investment will multiply,
as baseline predictive model costs plunge.
Managers will also deliver more actionable feedback,
as model details communicate more clearly.

### Risks

Every predictive model conditions on quality input data.
Without quality data, there's no expected return on predictive modeling.


## Scope and Limitations

### Limitations and Exclusions

This problem focuses not on predictive modeling algorithms, 
but on the pre-modeling data transform pipeline.  


## Business Context

### Stakeholder Profiles

- Model developers
  - Varying degrees of expertise in coding, data analysis
  - Incentivized to quickly deliver accurate analysis
  - Rewarded for increasing productivity
  - Interested in problem-critical code details, and complexity management
  - Uninterested in re-inventing the wheel project-to-project
- Business managers
  - Experts in business needs
  - Incentivized to solve business needs with data
  - Interested in problem-critical model details, and guiding project direction

### Project Priorities

This product prioritizes quality above all else, 
because it doesn't face schedule or cost pressures.
This product will have low staff allowance, for the foreseeable future.

### Deployment Considerations

In its early stage, this product's interface will be programmatic,
for an end user with some coding experience. 

Longer-term, a graphical user interface could democratize the workflow
for non-coders.